### ISSUE TITLE
Reserved error (-7701); there is no message for this error.

### ISSUE THREAD

**Issue by tombatron** [redis-field-engineering/redis-sql-odbc-dist#4]
Hi friends!

This is more of a question than an "issue". 

Within Microsoft Access (Office 365) I go to create an ODBC connection, selecting "Link to the data source by creating a linked table", I select a "Machine Data Source" and then configure an ODBC connection to Redis I get this error message:

![image](https://github.com/redis-field-engineering/redis-sql-odbc-dist/assets/119369/14828e85-8fc6-4b6f-8f92-9eef8c3cdd01)

Using the same configured data source in Excel seems to work. 

Is this something anyone's encountered?

**Comment by slorello89** [comment]
Hi Tom,

I'm getting the same thing in Access (I've never tried using Access to access a Redis ODBC data source) - it looks like Access might not like the feature set advertised by the driver, I see that it's calling `SQLGetInfo` a few times and then exiting specifically it's checking:

`SQL_CURSOR_COMMIT_BEHAVIOR` - which is set to `SQL_CB_PRESERVE`
`SQL_CURSOR_ROLLBACK_BEHAVIOR` which also is set to `SQL_CB_PRESERVE`
`SQL_GETDATA_EXTENSIONS` which is set to `SQL_GD_ANY_COLUMN | SQL_GD_ANY_ORDER | SQL_GD_BOUND`
`SQL_ODBC_API_CONFORMANCE` which is set to `SQL_OAC_LEVEL1`

Not entirely sure why it would be exiting given this, but that's all I see happening on my end - doesn't look like there's any ODBC/Run-time Errors, or really anything hinky emanating out of driver. I think it just might be that the Access Driver want's some kind of live-updates from the datasource (which it is not setup to provide)

**Comment by tombatron** [comment]
Fair enough my man. Thanks for looking!
